include("/opt/homebrew/share/cmake/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[test_main]==]
  TEST_EXECUTABLE [==[/Users/yue/Workspace/SLIMED/bin/test_main]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[/Users/yue/Workspace/SLIMED]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[test_main_TESTS]==]
  CTEST_FILE [==[/Users/yue/Workspace/SLIMED/tests/test_main_302383d8_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[/Users/yue/Workspace/SLIMED/tests]==]
)
