/**
 * @file io.hpp
 * @author Y Ying (yying7@jh.edu)
 * @brief Manage io of continuum membrane model, including
 * parameter files, vertices and faces, and scaffolding structure
 * files.
 * @date 2023-03-29
 * 
 * @copyright Copyright (c) 2023
 * 
 */
#pragma once 

#include <fstream>
#include <sstream>
#include <iostream>
#include <stdlib.h>
#include <string>
#include <vector>
#include <stdexcept>
#include <sys/stat.h>

#include "mesh/Mesh.hpp"
#include "model/Record.hpp"
#include "model/Model.hpp"
#include "mesh/Vertex.hpp"
#include "Parameters.hpp"
#include "linalg/Linear_algebra.hpp"
#include "Dynamics.hpp"

/**
 * @brief Remove spaces, tabs and carriage returns from a string
 *
 * This function takes a raw string and removes every whitespace character present
 * in it (\s, \t and \r). The carriage return matters: getline() splits on
 * '\n', so a CRLF-terminated line keeps a trailing '\r', and leaving it in place
 * silently defeats the exact value comparisons in import_kv_string() -- notably
 * boundaryType, where 'Periodic\r' fell through to BoundaryType::Fixed.
 *
 * @param rawString the original string to be processed
 *
 * @return The string with spaces, tabs and carriage returns removed.
 */
std::string pop_space(std::string rawString);

std::string trim_trailing_semicolon(std::string rawString);

/**
 * @brief Remove trailing carriage returns from a string
 *
 * getline() splits on '\n', so a CRLF-terminated line keeps a trailing '\r'.
 * Strip it before parsing so an invisible character cannot defeat the exact value
 * comparisons in import_kv_string(). .gitattributes keeps checkouts LF; this
 * covers files that were hand-edited on Windows.
 *
 * @param rawString the original string to be processed
 *
 * @return The string with trailing carriage returns removed.
 */
std::string trim_trailing_cr(std::string rawString);

/**
 * @brief Import key-value pairs from a string
 *
 * This function takes two strings, `variableNameStr` and `variableValueStr`, which are expected to contain name-value pairs separated by 
 * an "=" sign. It then parses these variables and uses them to update a `Param` struct object's variables, which is passed as reference. 
 * If parsing and updating are successful, returns true, else returns false.
 *
 * @param variableNameStr the string containing names of the variables
 * @param variableValueStr the string containing values of the variables 
 * @param param the Param object to be updated 
 *
 * @return true if parsing and updating was successful, else false.
 */
bool import_kv_string(std::string variableNameStr, std::string variableValueStr, Param& param);

/**
 * @brief Import parameters from a file
 *
 * This function reads a parameter file specified by `filepath` and updates a `Param` struct object's variables using the information present
 * in the file. The updated `Param` object is passed as reference. If file reading and updating are successful, returns true, else false.
 *
 * @param param the Param object to be updated
 * @param filepath the path of the parameter file to be read
 *
 * @return true if file reading and updating was successful, else false.
 */
bool import_param_file(Param& param, std::string filepath);

/**
 * @brief Read data from a CSV file and store it in a vector of vectors with the specified data type.
 *
 * This function reads data from a CSV file, where each line represents a row of data,
 * and each value within a line is separated by the specified character.
 * 
 * Generated by GPT 3.5.
 *
 * @tparam T The data type (int, float, or double) to store in the resulting vector.
 * @param filepath The file path of the CSV file.
 * @param separator The character used as a separator in the CSV file (default is comma ',' for typical CSV files).
 * @return A vector of vectors containing the read data.
 * @throws std::invalid_argument If the data cannot be converted to the specified data type.
 */
template <typename T>
std::vector<std::vector<T>> read_data_from_csv(const std::string& filepath, char separator = ',') {
    // Open and read CSV file
    std::ifstream csvFile(filepath);
    if (!csvFile.is_open()) {
        // Handle error: Unable to open CSV file
        throw std::invalid_argument("Unable to open CSV file.");
    }

    // Data structure to store data
    std::vector<std::vector<T>> data;

    // Read each line from the CSV file
    std::string line;
    while (std::getline(csvFile, line)) {
        std::vector<T> row;
        std::istringstream iss(line);
        std::string value;

        // Parse the line using the specified separator
        while (std::getline(iss, value, separator)) {
            try {
                T typedValue = static_cast<T>(std::stod(value));
                row.push_back(typedValue);
            } catch (const std::invalid_argument& e) {
                // Handle error: Unable to convert to the specified data type
                csvFile.close(); // Close CSV file before throwing exception
                throw std::invalid_argument("Unable to convert data to the specified data type.");
            }
        }

        // Add the row to the data vector
        data.push_back(row);
    }

    // Close the CSV file
    csvFile.close();

    return data;
}

/**
 * @brief The mesh files: a vertex file and a faces file.
 *
 * Both are comma-separated (a line with no comma is split on whitespace),
 * blank lines and lines starting with '#' are skipped, and a trailing empty
 * field is ignored.
 *
 * The vertex file is one vertex per line, indexed from zero in file order:
 *
 *     x, y, z                     an ordinary (free) vertex
 *     x, y, z, type               type: free | fixed | periodic | ghost
 *     x, y, z, periodic, mirror   a periodic image of vertex `mirror`
 *
 * The type column may also carry the integer values of VertexType, which is
 * what the legacy Mesh::write_vertices_csv_with_type() writes. A periodic
 * vertex must name the vertex it mirrors; a chain of mirrors is flattened at
 * setup. The offset between an image and its source is read off their
 * coordinates, so the file's positions have to be right.
 *
 * The faces file is one triangle per line, three vertex indices wound
 * consistently, with an optional fourth column saying whether the face is a
 * copy of another physical face (0 or "real", 1 or "copy"):
 *
 *     v0, v1, v2
 *     v0, v1, v2, copy
 *
 * Without that column the copies are derived from the mirror map
 * (Mesh::mark_periodic_copy_faces()). export_mesh_to_vertices_faces() writes
 * both files in this format with every column, so a mesh SLIMED wrote loads
 * back exactly.
 *
 * A file with any type other than free needs boundaryType = Mixed; the
 * global modes decide the boundary from grid position and refuse the file
 * rather than ignore it.
 * 
 * @see docs/mixed_boundary_conditions.md
 */
struct MeshFileData
{
    std::vector<std::vector<double>> vertices; ///< x, y, z per vertex
    std::vector<std::vector<int>> faces;       ///< three corner indices per face
    std::vector<VertexType> types;             ///< one per vertex; empty when the file has no type column
    std::vector<int> mirrors;                  ///< one per vertex, -1 unless a periodic image; empty with types
    std::vector<char> faceIsCopy;              ///< one per face; empty when the faces file has no flag column

    /// Whether any vertex asks for something other than free.
    bool has_boundary_types() const
    {
        for (VertexType type : types)
        {
            if (type != VertexType::Free)
            {
                return true;
            }
        }
        return false;
    }
};

/**
 * @brief Read a vertex file and a faces file, without touching a mesh.
 *
 * @throw std::invalid_argument naming the file and line on anything it cannot
 *        read: a missing coordinate, an unknown type, a periodic vertex with
 *        no mirror, a corner index outside the vertex file.
 */
MeshFileData read_mesh_vertices_faces_files(const std::string &verticesFilepath,
                                            const std::string &facesFilepath);

/**
 * @brief Import a mesh from separate files containing vertices and faces.
 *
 * Reads both files (read_mesh_vertices_faces_files()) and sets the mesh up
 * from them, boundary types included. A template so that a DynamicMesh gets
 * its own setup -- the one that also builds the coordinate matrices -- rather
 * than Mesh's.
 *
 * @param mesh The Mesh (or DynamicMesh) to set up.
 * @param verticesFilepath The file path of the vertices file.
 * @param facesFilepath The file path of the faces file.
 * @return True if the mesh is successfully imported. Failure throws.
 */
template <class MeshT>
bool import_mesh_from_vertices_faces(MeshT &mesh, std::string verticesFilepath,
                                     std::string facesFilepath)
{
    const MeshFileData data = read_mesh_vertices_faces_files(verticesFilepath, facesFilepath);
    mesh.setup_from_vertices_faces(data.vertices, data.faces, data.types, data.mirrors,
                                   data.faceIsCopy);
    return true;
}

/**
 * @brief Write a mesh as a vertex file and a faces file that
 * import_mesh_from_vertices_faces() reads back exactly.
 *
 * Every column is written: coordinates to full precision, the type of every
 * vertex, the mirror of every periodic image, and the copy flag of every
 * face. Meant for a mesh built under BoundaryType::Mixed; under a global
 * mode the ghost band is written as ghost scaffolding, without the periodic
 * identification the grid carried.
 *
 * @throw std::runtime_error if either file cannot be opened.
 */
void export_mesh_to_vertices_faces(const Mesh &mesh, const std::string &verticesFilepath,
                                   const std::string &facesFilepath);

/// Whether the parameters ask for the mesh to be loaded from files.
inline bool mesh_comes_from_files(const Param &param)
{
    return !param.meshVerticesFile.empty() || !param.meshFacesFile.empty();
}

/**
 * @brief Build the run's mesh the way the parameters say: from the mesh
 * files when meshVerticesFile and meshFacesFile are set, otherwise the
 * generated flat sheet.
 *
 * @throw std::runtime_error if only one of the two files is set.
 */
template <class MeshT>
void setup_mesh_from_parameters(MeshT &mesh)
{
    const Param &param = mesh.param;
    if (!mesh_comes_from_files(param))
    {
        mesh.setup_flat();
        return;
    }
    if (param.meshVerticesFile.empty() || param.meshFacesFile.empty())
    {
        throw std::runtime_error(
            "[setup_mesh_from_parameters] meshVerticesFile and meshFacesFile must be set "
            "together; got meshVerticesFile = '" +
            param.meshVerticesFile + "' and meshFacesFile = '" + param.meshFacesFile + "'");
    }
    std::cout << "[setup_mesh_from_parameters] Loading the mesh from " << param.meshVerticesFile
              << " and " << param.meshFacesFile << std::endl;
    import_mesh_from_vertices_faces(mesh, param.meshVerticesFile, param.meshFacesFile);
}

/**
 * @brief Import scaffolding mesh from a file
 *
 * This function reads a mesh file specified by `filepath` and returns a vector of matrices containing the vertices' coordinates of all
 * triangular faces. 
 *
 * @param filepath the path of the mesh file to be read
 *
 * @return A vector of matrices containing the vertices' coordinates of all triangular faces.
 */
std::vector<Matrix> import_scaffolding_mesh(std::string filepath);

/**
 * 
 * @deprecated Use Mesh::write_vertex_data_to_csv instead
 * @brief Writes the vertex data for the mesh to a CSV file.
 *
 * This function writes the coordinates of each vertex in the mesh to a CSV file named "vertex[nFile].csv", where nFile is
 * equal to iteration/100. The output is formatted as follows:
 *
 *     x1,y1,z1
 *     x2,y2,z2
 *     ...
 *
 * where xi, yi, and zi are the coordinates of the ith vertex in the mesh.
 * 
 * @note Step size and file name are left in definition in case customization is needed.
 *
 * @param mesh The mesh whose vertex data should be written to a CSV file.
 * @param iteration The current iteration number of the optimization algorithm.
 */
void write_vertex_data_to_csv(const Mesh &mesh, const int iteration)
__attribute__((deprecated("Use Mesh::write_vertex_data_to_csv instead.")));

/**
 * @brief Writes the energy force data to a CSV file.
 *
 * This function writes the energy and force data for each iteration in the following format:
 * 
 * "E_Curvature, E_Area, E_Regularization, E_Total ((pN.nm)), Mean Force (pN)"
 * 
 * @note File name is left in definition in case customization is needed.
 *
 * @param model The model that cotains a mesh whose vertex data should be written to a CSV file.
 *
 */
void write_energy_force_data_to_csv(const Model &model);

/**
 * @brief Write a restart checkpoint for a minimization model.
 *
 * The checkpoint stores the iteration to run next, optimization state, mesh
 * coordinates, scaffold state, and record history needed to continue a Slurm
 * job after a walltime stop.
 */
bool write_model_restart_checkpoint(const Model &model,
                                    const std::string &filepath,
                                    const int nextIteration);

/**
 * @brief Load a restart checkpoint into an initialized minimization model.
 */
bool load_model_restart_checkpoint(Model &model, const std::string &filepath);

/**
 * @brief Writes the current iteration element face energy data to a CSV file.
 *
 * This function writes the energy data for each element face of
 *  the current iteration in the following format:
 *
 * "E_Curvature, E_Area, E_Regularization, E_Total"
 *
 * @note @note File name is left in definition in case customization is needed.
 *
 * @param model The model that cotains a mesh whose vertex data should be written to a CSV file.
 *
 * 
 */
void write_element_face_energy_to_csv(const Model &model);

/**
 * @brief Writes the last vertex data for the mesh to a CSV file.
 *
 * This function writes the coordinates of each vertex in the last step 
 * in the mesh to a CSV file named "vertexfinal.csv". The output is formatted as follows:
 *
 *     x1,y1,z1
 *     x2,y2,z2
 *     ...
 *
 * where xi, yi, and zi are the coordinates of the ith vertex in the mesh.
 * 
 * @note file name are left in definition in case customization is needed.
 *
 * @param mesh The mesh whose vertex data should be written to a CSV file.
 */
void write_final_vertex_data_to_csv(const Mesh &mesh);

/**
 * @brief Create surface point and mesh point trajectory files.
 * 
 * File output: surfacepoint<filename>.csv; meshpoint<filename>.csv
 * 
 * @param filename 
 */
void dynamics_create_trajectory_files(DynamicMesh &mesh, const std::string &filename);

/**
 * @brief Construct a new output trajectory files object
 * 
 * @param mesh 
 * @param input_filename 
 */
void output_trajectory_files(Mesh &mesh, const std::string &input_filename);

/**
 * @brief Open surface point and mesh point trajectory files and append to
 * the files with current data.
 * 
 * Files: surfacepoint<filename>.csv; meshpoint<filename>.csv
 * 
 * @param filename
 * 
 */
void dynamics_output_trajectory_files(DynamicMesh &mesh, const std::string &filename);

/**
 * @brief Write the connectivity beside a trajectory frame, if it has changed.
 *
 * A run with edge flips has no single face list. `<filename>face.csv`, written
 * once at setup, describes the mesh the run *started* with, and every analysis
 * that pairs it with a later coordinate frame -- the fluctuation spectrum
 * included -- silently reads the wrong triangles. So each frame whose
 * connectivity differs from the last one written gets its own
 * `<filename>face_<iteration>.csv`, and a frame is paired with the most recent
 * such file at or before its iteration.
 *
 * Nothing is written when the connectivity has not moved, which is every frame
 * of a run with flips off: the setup-time `face.csv` still describes those
 * runs completely and their output is unchanged.
 *
 * @param iteration The frame's iteration, which names the file.
 * @return true if a file was written.
 */
bool dynamics_output_face_frame(DynamicMesh &mesh, const std::string &filename,
                                long long iteration);
