name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev libgsl-dev

    - name: Make serial
      run: |
        make clean
        make serial

    - name: Make and run unit test
      run: |
        make clean
        make test
        ./bin/test_main
